### PR TITLE
[Feature] Refactor matrix scanning implementation

### PR DESCRIPTION
**Pull request by KarlK90**
## Description

Hi @JohnAZoidberg and Framework :wave:,

QMK maintainer and author of the RP2040 port here. I've followed your announcement of the Framework 16 and was pretty much blown away, such a cool product/project. As I heard that the input modules would be based on QMK and the RP2040 I naturally had to take a look. Reading through the issues I stumbled upon https://github.com/FrameworkComputer/qmk_firmware/issues/8 which kinda scratched an itch :wink:. So here is an PR with a refactoring of the matrix scanning implementation.

I've tested it as best a possible on a RPi Pico as I don't have a Framework 16 (yet?)

## Details

The former matrix scan implementation (for the ISO variant) caped at around ~500Hz which is around half of the USB full speed bandwidth. As QMK is one big busy loop the faster the matrix scanning is done, the more cycles are available for further QMK shenanigans. This refactored implementation is around 4x faster and sits at ~2.1kHz on a pico proto board which gives good headroom.

The following changes brought the biggest wins:

1. Use the `pico-sdk` ADC reading implementation as it uses busy waiting which has much less overhead compared to the current ChibiOS implementation that has context switching overhead.
2. Pre-compute all row and col to pin lookups.
3. Use whole port based IO to set multiple pins at once, instead of setting each pin individually.

For correctness the scanning now dynamically waits for all IO pins/ports to reach their expected target level before attempting to read matrix changes.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/FrameworkComputer/qmk_firmware/issues/8

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by JohnAZoidberg** [comment]
That is awesome! Thanks so much for the help!

I'll check it out in detail after the weekend.
I just tested it on the full size keyboard where it can reach ~1250Hz now. Compared to 500Hz previously.
On the numpad module it goes from ~2350Hz to ~5750Hz.

**Comment by KarlK90** [comment]
> That is awesome! Thanks so much for the help!

You're welcome.

> I'll check it out in detail after the weekend. I just tested it on the full size keyboard where it can reach ~1250Hz now. Compared to 500Hz previously. On the numpad module it goes from ~2350Hz to ~5750Hz.

That is a nice gain, I suspect that the fall and rise times on real hardware are longer (because of the capacitance of the wires/matrix) than on my Pico protoboard.

**Comment by JohnAZoidberg** [comment]
Hey, sorry, I will get back to this. It's a really great improvement that we definitely want in one way or another.
But it's not working well in the current implementation. Some keys don't work and n-key rollover is worse.

**Comment by KarlK90** [comment]
No problem, I don't have access to real hardware so verification and bug fixing wasn't possible on my side.

**Comment by KarlK90** [comment]
Rebased and fixed merge conflicts.

**Comment by nyabinary** [comment]
Maybe that the FW16 has been opened for preorders this can be worked on again?

**Comment by KarlK90** [comment]
Bump.

**Comment by KarlK90** [comment]
@JohnAZoidberg could you remove the stale label, I still want to work on this.

**Pull request closed without merging**
